[package]
name = "rustc-build-sysroot-emscripten"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.5.24"
clap_derive = "4.5.24"
rustc-build-sysroot = "0.5.4"
